# Generated by Django 6.0.3 on 2026-03-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilfield', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('operator_company', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('pressure', 'Pressure'), ('temperature', 'Temperature'), ('flow_rate', 'Flow Rate')], max_length=20)),
                ('install_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mockitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProductionReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='oilfield.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('shut-in', 'Shut-in'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('drill_date', models.DateField()),
                ('depth_m', models.FloatField()),
                ('oil_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='oilfield.oilfield')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='oilfield.well'),
        ),
    ]
